title: FAIR Vocabularies Examples
description: Examples of FAIR vocabularies and their guidelines
theme: jekyll-theme-minimal

baseurl: /examples

# plugins:
#   - jekyll-relative-links
# relative_links:
#   enabled: true
#   collections: true

include:
  - domains
  - identifiers
  - vocabularies

exclude:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
